"""Dumps every user-facing string of the UI as an identity dictionary, ready to translate.

`language/en.json` is generated by this tool: it lists the labels, values, info texts, choices and
placeholders of all Gradio components, each mapped to itself. To translate the UI, copy that file to
`language/<code>.json` (for example `language/zh.json`), replace the values, and start ReFocus with
`--language zh`. Strings the file does not mention stay in English.

Usage (from the repository root, with the same interpreter the app uses):

    python tools/dump_ui_strings.py            # rewrite language/en.json
    python tools/dump_ui_strings.py --print    # print the count and a sample, write nothing
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)


def collect_strings():
    """Every translatable string in the built UI, as a sorted identity dictionary."""
    import modules.webui as webui

    texts = set()
    for component in webui.gradio_root.get_config_file()['components']:
        props = component.get('props') or {}
        for key in ('label', 'value', 'info', 'placeholder'):
            value = props.get(key)
            if isinstance(value, str) and value:
                texts.add(value)
        for choice in props.get('choices') or []:
            if isinstance(choice, (list, tuple)):
                for item in choice:
                    if isinstance(item, str) and item:
                        texts.add(item)
            elif isinstance(choice, str) and choice:
                texts.add(choice)

    return {text: text for text in sorted(texts) if 'progress-container' not in text}


def main():
    strings = collect_strings()
    target = os.path.join(ROOT, 'language', 'en.json')

    if '--print' in sys.argv[1:]:
        print(f'{len(strings)} strings; first 10: {list(strings)[:10]}')
        return 0

    import json
    with open(target, 'w', encoding='utf-8', newline='') as f:
        json.dump(strings, f, indent=4, ensure_ascii=False)
        f.write('\n')
    print(f'Wrote {len(strings)} strings to {target}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
